### ISSUE TITLE
需要增加 .gitignore 文件

### ISSUE THREAD

**Issue by hexsix** [dali-yy/video-player#1]
你可能需要忽略一些编译文件，比如 `__pycache__/videoPlayer.cpython-37.pyc`，参考：[git 忽略特殊文件](https://www.liaoxuefeng.com/wiki/896043488029600/900004590234208)

但是 `.gitignore` 只能忽略没有 commit 的文件，参考：[git 配置.gitignore 删除已提交的文件](https://blog.csdn.net/weixin_35757704/article/details/119672173)

> saki 时间线来的，对，就是那个 star

**Comment by dali-yy** [comment]
谢谢您的建议



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月14日(周四) 下午3:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dali-yy/video-player] 需要增加 .gitignore 文件 (Issue #1)




 
你可能需要忽略一些编译文件，比如 __pycache__/videoPlayer.cpython-37.pyc，参考：git 忽略特殊文件
 
但是 .gitignore 只能忽略没有 commit 的文件，参考：git 配置.gitignore 删除已提交的文件
  
saki 时间线来的，对，就是那个 star
